"""Build the Session 8 deck from its parts. Shares kit.py (deckgen-s1) and
common.py and svgkit.py (deckgen-s3).

    cd scripts/deckgen-s8 && python3 build.py

Writes lectures/kr-session-08.html (instructor-approved 2026-09-26). Edit the parts and rebuild; never hand-edit
the HTML. The day follows module-08-defense/DEFENSE-DAY.md and the
syllabus; the checklist is the one agreed in Session 7.
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(1, str(HERE.parent / "deckgen-s3"))
sys.path.insert(2, str(HERE.parent / "deckgen-s1"))
import part1  # noqa: E402

out = sys.argv[1] if len(sys.argv) > 1 else "../../lectures/kr-session-08.html"
slides = part1.SLIDES
total = sum(int(re.search(r'data-minutes="(\d+)"', s).group(1)) for s in slides)

HEAD = f'''<!DOCTYPE html>
<html lang="en" class="lu-deck-page">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>The Defense · Knowledge Representation, Session 8</title>
<meta name="description" content="Session 8 of Knowledge Representation, MSc, Lebanese University. The defense day: the order of the day, one team's slot, how students are marked, the defenses, and the course close.">
<meta name="theme-color" content="#96122B">
<link rel="manifest" href="../manifest.webmanifest">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,500;0,8..60,600;1,8..60,400&family=IBM+Plex+Sans:ital,wght@0,400;0,500;0,600;1,400&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../assets/lu.css?v=1.3.0">
</head>

<!-- Generated by scripts/deckgen-s8/build.py. Edit the parts there, then rebuild. -->
<body
  data-deck-id="kr-s08"
  data-course="Knowledge Representation"
  data-session="Session 8 of 8"
  data-duration="{total}"
  data-app-root="../"
  data-unit="Lebanese University · MSc">

<a class="lu-skip" href="#slide-2">Skip to the first content slide</a>

<div class="deck">
<div class="deck__stage">

'''
TAIL = '''
</div><!-- /stage -->
</div><!-- /deck -->

<script src="../assets/glossary.js?v=1.0.0" defer></script>
<script src="../assets/lu-glossary.js?v=1.0.0" defer></script>
<script src="../assets/lu-deck.js?v=1.1.0" defer></script>
<script src="../assets/lu-flow.js?v=1.2.1" defer></script>
</body>
</html>
'''
body = "\n".join(f"<!-- {'=' * 68} {i:02d} -->\n{s}" for i, s in enumerate(slides, 1))
Path(out).write_text(HEAD + body + TAIL, encoding="utf-8")
print(f"{out}: {len(slides)} slides, {total} minutes")
