"""Session 4, Part 4: provenance with PROV-O, and a version IRI.

Numbers: reference-outputs/add-provenance.txt, provenance-sample.ttl,
version-ontology.txt (2026-09-25).
"""
from common import slide, divider, defbox, callout, code
from kit import flow, node, edge

SLIDES = []

K = '<span class="tok-kw">'
S = '<span class="tok-str">'
C = '<span class="tok-com">'
V = '<span class="tok-var">'
E = '</span>'

SLIDES.append(divider("Part 4 · Provenance and versions", "Provenance",
    "Part 4 of 5 · about 17 minutes",
    "Order 1447296446.7 is carried by V44_3. Says who, and since when?",
    "A triple without its history cannot be trusted, or fixed."))

# ---------------------------------------------------------------- PROV-O in three kinds of box
n = [
    node("g", "Entity · named graph OrderList\n119,844 triples", 290, 40, 470, 62, kind="individual"),
    node("f", "Entity · file OrderList.csv", 290, 155, 470, 56, kind="individual"),
    node("r", "Activity · conversion run\nended 2026-09-25 01:31 UTC", 860, 155, 380, 62, kind="individual"),
    node("p", "Agent · program\nconvert_to_rdf.py", 1250, 40, 300, 62, kind="builtin"),
]
e = [
    edge("a", "g", "f", "was derived from"),
    edge("b", "g", "r", "was generated by", route="elbow", sides=["right", "top"]),
    edge("c", "r", "f", "used"),
    edge("d", "r", "p", "associated with", route="elbow", sides=["right", "bottom"]),
]
steps = [
    {"show": ["g", "f", "a"], "run": ["a"], "set": {"g": "active"}},
    {"show": ["r", "b", "c"], "run": ["b", "c"], "set": {"g": "idle", "r": "active"}},
    {"show": ["p", "d"], "run": ["d"], "set": {"r": "idle", "p": "active"}},
]
caps = [
    ("Where it came from", "<b>Step 1.</b> An <b>entity</b> is a thing: the named graph OrderList was derived from another entity, the file OrderList.csv."),
    ("How and when", "<b>Step 2.</b> An <b>activity</b> is something that happened: a conversion run used the file and generated the graph."),
    ("Who", "<b>Step 3.</b> An <b>agent</b> is responsible: here a program, Session 2's convert_to_rdf.py, recorded with its checksum."),
]
walk = flow("Provenance of the OrderList graph", 1448, 190, n, e, steps, caps,
            legend={"individual": "Recorded provenance", "builtin": "Program"})
SLIDES.append(slide("PROV-O: entity, activity, agent", "Provenance", 5, '''  <div class="lu-eyebrow">Provenance, drawn</div>
  <h2 class="lu-h2">Three kinds of thing answer &ldquo;where from, how, and who&rdquo;</h2>
  ''' + walk + '''
  <div class="lu-split">
    ''' + defbox([("Provenance", "The record of where data came from, who produced it, and how.")]) + '''
    ''' + defbox([("PROV-O", "The W3C ontology for writing provenance as triples: entities, activities, agents.")], label="Also defined here") + '''
  </div>''', '''<p>Five minutes. The graph is real: <code>python add_provenance.py</code> wrote 43 triples of provenance about the four Brunel named graphs of Session 2 (<code>reference-outputs/add-provenance.txt</code>). The run time is the file time of <code>brunel.trig</code>, so it differs on every laptop.</p>
<ul><li>This works because Session 2 put each table in its own named graph. Provenance is recorded per graph, not per triple: 43 triples describe 135,792 data triples.</li>
<li>Each file entity carries its SHA-256 checksum, so a changed CSV is detectable.</li></ul>'''))

# ---------------------------------------------------------------- Asking where a fact came from
q = (f'''{K}SELECT{E} {V}?g{E} {V}?file{E} {V}?run{E} {V}?time{E} {K}WHERE{E} {{
  {K}GRAPH{E} {V}?g{E} {{
    order:1447296446.7 ul:carriedBy {V}?c{E} }}
  {K}GRAPH{E} {V}?p{E} {{
    {V}?g{E} prov:wasDerivedFrom {V}?f{E} ;
       prov:wasGeneratedBy {V}?run{E} .
    {V}?f{E} dcterms:title {V}?file{E} .
    {V}?run{E} prov:endedAtTime {V}?time{E} }} }}''')
out = (f'''graph     graph/brunel/OrderList
file      OrderList.csv
run       run/brunel/
            convert-20260925T013112Z
finished  2026-09-25T01:31:12+00:00''')
SLIDES.append(slide("Asking where a fact came from", "Provenance", 4, '''  <div class="lu-eyebrow">Provenance is queryable</div>
  <h2 class="lu-h2">One SPARQL query walks from a triple to its file, its run and its time</h2>
  <div class="lu-split">
    ''' + code("add_provenance.py · the question", q) + '''
    <div class="lu-stack">
      ''' + code("the real answer (IRIs after .../kr/id/)", out) + '''
      ''' + callout("Why it matters today", "When triage says &ldquo;data wrong&rdquo;, this is how you find which file to fix, and prove later which run fixed it.") + '''
    </div>
  </div>''', '''<p>Four minutes. Read the answer aloud as a sentence: the fact came from OrderList.csv, through this run, finished at this time.</p>
<ul><li>The two zero weight orders of Part 2: the same query tells you they came from OrderList.csv, which is where the fix belongs, not in the graph.</li></ul>'''))

# ---------------------------------------------------------------- Versioning the ontology
hdr = (f'''&lt;https://ul.edu.lb/kr/scm#&gt; {K}a{E} owl:Ontology ;
  owl:versionIRI &lt;https://ul.edu.lb/kr/scm/1.0.0&gt; ; {C}# new{E}
  owl:versionInfo {S}"1.0.0"{E} ;                       {C}# new{E}
  rdfs:label {S}"UL Knowledge Representation ..."{E} ;
  owl:imports &lt;https://spec.industrialontologies.org/
      ontology/supplychain/SupplyChain/&gt; .''')
SLIDES.append(slide("Versioning the ontology", "Provenance", 4, '''  <div class="lu-eyebrow">Release discipline</div>
  <h2 class="lu-h2">The ontology IRI names the ontology. A version IRI names one release of it.</h2>
  ''' + code("python version_ontology.py · the Session 3 ontology, released as 1.0.0", hdr) + '''
  <div class="lu-split">
    ''' + defbox([("Version IRI", "The name of one release of an ontology (<code>owl:versionIRI</code>), next to the ontology IRI that names all its releases.")]) + '''
    ''' + callout("Why shapes need it", "Shapes are written against one release. Import the version IRI you validated against, and a later change to the ontology cannot silently break your checks.") + '''
  </div>''', '''<p>Four minutes. Real run: the Session 3 reference file had no version IRI at all (176 triples); the release has 178 (<code>reference-outputs/version-ontology.txt</code>). The script writes a new file; Session 3's file is not changed.</p>
<ul><li>The next release gets a new version IRI and points back with <code>owl:priorVersion</code>. Milestone 1 asks each team for exactly this on its own ontology.</li></ul>'''))

# ---------------------------------------------------------------- Drill
SLIDES.append(slide("Drill: provenance words", "Provenance", 3, '''  <div class="lu-eyebrow">Drill · type the missing word</div>
  <div class="lu-blanks" data-qid="s4-blanks2" data-label="Provenance and versioning words">
    <p class="lu-h3" style="margin-bottom:var(--lu-s4)">Fill in the blanks</p>
    <ol class="lu-list lu-list--num">
      <li>The named graph OrderList <code>prov:</code><input class="lu-blank lu-blank--wide" data-answer="wasDerivedFrom|was derived from" data-label="Blank 1" placeholder="…"> the file OrderList.csv.</li>
      <li>A conversion run is a PROV <input class="lu-blank" data-answer="activity|prov:Activity" data-label="Blank 2" placeholder="…">; the program that ran it is an <input class="lu-blank" data-answer="agent|prov:Agent|SoftwareAgent|prov:SoftwareAgent" data-label="Blank 3" placeholder="…">.</li>
      <li>One release of an ontology is named with <code>owl:</code><input class="lu-blank lu-blank--wide" data-answer="versionIRI|version IRI" data-label="Blank 4" placeholder="…">.</li>
    </ol>
  </div>''', '''<p>Three minutes. Blank 1 is the one students use in Milestone 1.</p>''', kind="tint"))
