"""Build lectures/kr-session-02.html from the four parts. Shares kit.py with deckgen-s1.

    cd scripts/deckgen-s2 && python3 build.py ../../lectures/kr-session-02.html
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(1, str(Path(__file__).resolve().parent.parent / "deckgen-s1"))
import part_a, part_b, part_c, part_d  # noqa: E402

out = sys.argv[1] if len(sys.argv) > 1 else "../../lectures/kr-session-02.html"
slides = part_a.SLIDES + part_b.SLIDES + part_c.SLIDES + part_d.SLIDES
total = sum(int(re.search(r'data-minutes="(\d+)"', s).group(1)) for s in slides)

HEAD = f'''<!DOCTYPE html>
<html lang="en" class="lu-deck-page">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RDF, SPARQL, and the Graph as a Data Model · Knowledge Representation, Session 2</title>
<meta name="description" content="Session 2 of Knowledge Representation, MSc, Lebanese University. A real Brunel order taken apart into triples, IRI design, RDFS and entailment, SPARQL with property paths and real timings, and RDF against the property graph.">
<meta name="theme-color" content="#96122B">
<link rel="manifest" href="../manifest.webmanifest">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,500;0,8..60,600;1,8..60,400&family=IBM+Plex+Sans:ital,wght@0,400;0,500;0,600;1,400&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../assets/lu.css?v=1.3.1">
</head>

<!-- Generated by scripts/deckgen-s2/build.py. Edit the parts there, then rebuild. -->
<body
  data-deck-id="kr-s02"
  data-course="Knowledge Representation"
  data-session="Session 2 of 8"
  data-duration="{total}"
  data-app-root="../"
  data-unit="Lebanese University · MSc">

<a class="lu-skip" href="#slide-2">Skip to the first content slide</a>

<div class="deck">
<div class="deck__stage">

'''
TAIL = '''
</div><!-- /stage -->
</div><!-- /deck -->

<script src="../assets/sparql-lite.js?v=1.1.0"></script>
<script src="../assets/glossary.js?v=1.0.0" defer></script>
<script src="../assets/lu-glossary.js?v=1.0.0" defer></script>
<script src="../assets/lu-deck.js?v=1.1.0" defer></script>
<script src="../assets/lu-flow.js?v=1.2.1" defer></script>
</body>
</html>
'''
body = "\n".join(f"<!-- {'=' * 68} {i:02d} -->\n{s}" for i, s in enumerate(slides, 1))
Path(out).write_text(HEAD + body + TAIL, encoding="utf-8")
print(f"{out}: {len(slides)} slides, {total} minutes")
