"""Cut a small, real slice of the Session 2 graph for the CI gate and the
Part B checker: a few Brunel orders, with everything the shapes need to
check them (their carriers, plants, ports, products, the plant links, and
every rate band of their lanes).

    python make_ci_sample.py

Writes, in ci/ (committed, so GitHub can validate without the 6 MB graph):
  sample-orders.ttl         the slice; passes the gate (one Warning)
  sample-orders-broken.ttl  the same with ONE value changed, a typo in a
                            carrier code (V444_0 written V444_O); fails
and, in part-b/, test-orders.ttl: the slice with four planted faults for
Part B, each on a real order and each listed in the file's header.
Run from demos/session-04-shacl/, after Session 2's convert_to_rdf.py.
"""

from pathlib import Path

from rdflib import RDF, RDFS, XSD, Graph, Literal, Namespace, URIRef

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / "session-02-rdf-sparql" / "brunel.ttl"
UL = Namespace("https://ul.edu.lb/kr/scm#")
ID = "https://ul.edu.lb/kr/id/"

# The course cast (AGENTS.md 2c rule 4) plus one order from the rate table's
# gap and one late order, so every shape has something real to look at.
ORDERS = [
    "1447296446.7",   # CRF, carrier V44_3 (Session 1's first row)
    "1447385217.7",   # carrier V444_0 (Session 3's sample shipments)
    "1447291369.7",   # carrier V444_1
    "1447311670.7",   # carrier V444_1
    "1447137127.7",   # weight in the rate table's gap (V444_1 · PORT04 · DTD)
]
BROKEN_ORDER, GOOD, TYPO = "1447385217.7", "V444_0", "V444_O"


def order(key):
    return URIRef(f"{ID}order/brunel/{key}")


def carrier(key):
    return URIRef(f"{ID}carrier/brunel/{key}")


def header(title, lines):
    return "".join(f"## {x}\n" for x in [title, ""] + lines + [""])


def main():
    big = Graph().parse(SOURCE)
    orders = [order(k) for k in ORDERS]
    late = [o for o in big.subjects(RDF.type, UL.LateOrder)
            if (o, UL.carriedBy, carrier("V444_0")) in big]
    orders.append(sorted(late, key=str)[0])  # the first late order of carrier V444_0

    g = Graph()
    g.bind("ul", UL)
    g.add((UL.LateOrder, RDFS.subClassOf, UL.Order))
    lanes = set()
    for o in orders:
        for p, v in big.predicate_objects(o):
            g.add((o, p, v))
        plant, prod = big.value(o, UL.fromPlant), big.value(o, UL.ofProduct)
        for node in [plant, prod] + [big.value(o, p) for p in (UL.carriedBy, UL.shipsFrom, UL.shipsTo, UL.orderedBy)]:
            for t in big.objects(node, RDF.type):
                g.add((node, RDF.type, t))
        for port in big.objects(plant, UL.servesPort):
            g.add((plant, UL.servesPort, port))
            g.add((port, RDF.type, UL.Port))
        if (plant, UL.makes, prod) in big:
            g.add((plant, UL.makes, prod))
        lanes.add(tuple(big.value(o, p) for p in (UL.carriedBy, UL.shipsFrom, UL.shipsTo, UL.serviceLevel)))
    for band in big.subjects(RDF.type, UL.RateBand):
        if tuple(big.value(band, p) for p in (UL.bandCarrier, UL.bandFrom, UL.bandTo, UL.bandService)) in lanes:
            for p, v in big.predicate_objects(band):
                g.add((band, p, v))
    keys = ", ".join(str(o).rsplit("/", 1)[-1] for o in orders)

    (HERE / "ci").mkdir(exist_ok=True)
    body = g.serialize(format="turtle")
    (HERE / "ci" / "sample-orders.ttl").write_text(header(
        "sample-orders.ttl: a real slice of the Session 2 graph, for the CI gate.",
        [f"{len(orders)} Brunel orders ({keys}),", "their carriers, plants, ports, products, plant links,",
         "and every rate band of their lanes. Generated by make_ci_sample.py; do not edit",
         "by hand, except on the demo branch that breaks the gate on purpose."]) + body)

    bad = Graph()
    bad.bind("ul", UL)
    bad += g
    bad.remove((order(BROKEN_ORDER), UL.carriedBy, carrier(GOOD)))
    bad.add((order(BROKEN_ORDER), UL.carriedBy, carrier(TYPO)))
    (HERE / "ci" / "sample-orders-broken.ttl").write_text(header(
        "sample-orders-broken.ttl: sample-orders.ttl with ONE value changed.",
        [f"Order {BROKEN_ORDER} is carried by {TYPO} (letter O) instead of {GOOD} (zero):",
         "a typo nobody would see in a spreadsheet. The gate must stop it."]) + bad.serialize(format="turtle"))

    # Part B: four planted faults, one per rule the student writes, on real orders.
    t = Graph()
    t.bind("ul", UL)
    t += g
    # Y1 exactly one customer, Y2 order date in 2013, Y3 CRF orders go by V44_3.
    other_customer = big.value(order("1447296446.7"), UL.orderedBy)
    faults = [
        ("1447385217.7", f"a second customer ({str(other_customer).rsplit('/', 1)[-1]}) as well as its own  [Y1]",
         lambda o: t.add((o, UL.orderedBy, other_customer))),
        ("1447291369.7", "no customer at all  [Y1]", lambda o: t.remove((o, UL.orderedBy, None))),
        ("1447311670.7", "order date 2031-05-26, the year's digits swapped  [Y2]",
         lambda o: (t.remove((o, UL.orderDate, None)), t.add((o, UL.orderDate, Literal("2031-05-26", datatype=XSD.date))))),
        ("1447135386.7", "service level CRF, but still carried by V444_0  [Y3]",
         lambda o: (t.remove((o, UL.serviceLevel, None)), t.add((o, UL.serviceLevel, Literal("CRF"))))),
    ]
    for key, _, fn in faults:
        fn(order(key))
    (HERE / "part-b").mkdir(exist_ok=True)
    (HERE / "part-b" / "test-orders.ttl").write_text(header(
        "test-orders.ttl: the CI slice with four PLANTED faults, for check_my_shapes.py.",
        ["Teaching data: real Brunel orders, each changed on purpose in one way:"]
        + [f"  order {k}: {d}" for k, d, _ in faults]
        + ["Every other order here is exactly as in the Session 2 graph."]) + t.serialize(format="turtle"))
    print(f"ci/sample-orders.ttl {len(g)} triples, {len(orders)} orders ({keys}); "
          f"ci/sample-orders-broken.ttl {len(bad)}; part-b/test-orders.ttl {len(t)}")


if __name__ == "__main__":
    main()
